backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
logo_url: https://affluere.netlify.com/images/affluere_original.png
collections:
  - name: 'nyheter'
    label: 'nyheter'
    folder: 'content/nyheter'
    create: true
    slug: '{{ slug }}' # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publicerat datum', name: 'date', widget: 'datetime' }
      - { label: 'Beskrivning', name: 'description', widget: 'string' }
      - { label: 'Bild', name: 'image', widget: 'image' }
      - { label: 'Innehåll', name: 'body', widget: 'markdown' }

  - label: "Data"
    name: "data"
    files: 
    - name: "priser"
      label: "Priser"
      file: "data/priceList.yml"
      extension: "yml"
      fields:
        - label: "Priser"
          name: "categories"
          widget: "list"
          fields:
            - {label: "title", name: "title", widget: "string"}
            - label: 'Prislista'
              name: 'priceList'
              widget: 'list'
              fields:
                - {label: Beskrivining, name: type, widget: string}
                - {label: Pris, name: price, widget: string}